### ISSUE TITLE
self xss is possible when doing a preview of markdown

### ISSUE THREAD

**Issue by efficienthacks** [Teradata/covalent-text-editor-nightly#11]
Enter in the following in the markdown editor:
`<img src='' onerror='alert(0)'>`

Click the toggle preview button and you'll see the alert.

However on the preview panel of [the demo](https://teradata.github.io/covalent/#/components/text-editor), there is no alert box rendered.

Other than that, great markdown editor for Angular - thanks for providing this.

**Comment by jeremysmartt** [comment]
Thanks for the Issue @efficienthacks , PR on the way 👍
