### ISSUE TITLE
Mention feature

### ISSUE THREAD

**Issue by omidkh68** [Teradata/covalent-text-editor-nightly#16]
is that possible to use mention feature?

**Comment by jeremysmartt** [comment]
Anything that is available in SimpleMDE is available in covalent-text-editor.  However, I don't see a `Mention` feature in SimpleMDE?

**Comment by omidkh68** [comment]
@jeremysmartt  In fact, I need the ability that show list of user by putting @ like instagram.

**Comment by jeremysmartt** [comment]
Please request this feature on the Simple MDE github
