### ISSUE TITLE
A way to disable input?

### ISSUE THREAD

**Issue by alexatstariongroup** [Teradata/covalent-text-editor-nightly#18]
I was unable to find any information relating to being able to disable input of the text editor programmatically. I need be able to make it readOnly at certain phases of operation.

**Comment by viccsjain** [comment]
There is a [PR ](https://github.com/sparksuite/simplemde-markdown-editor/pull/607/commits/8b6dec9c46f263b7cde8fb4fa916aa0d23231c33)already raised in SmipleMDE for disabled as configuration option. Once this got merged, you can pass disabled as configurable option.

**Comment by viccsjain** [comment]
Hi @alexatrhea,

For time being, you can also try this

Typescript:
```
export class DocsAppComponent implements AfterViewInit {
  @ViewChild('editor') editor: TdTextEditorComponent;

  ngAfterViewInit() {
    this.editor.value = 'this is **examaple** markdown';
    this.editor.simpleMDE.codemirror.options.readOnly = true;
  }
}

```

HTML:

`<td-text-editor #editor></td-text-editor>
`

Stackblitz: https://covalent-text-editor.stackblitz.io

**Comment by emoralesb05** [comment]
Probably a good one to have as an input in the component.

**Comment by viccsjain** [comment]
Sure @emoralesb05,
I will raise PR for same.
