### ISSUE TITLE
Grammarly chrome extension is not working in this editor

### ISSUE THREAD

**Issue by raj2033** [Teradata/covalent-text-editor-nightly#24]
I have integrated this editor in my web application. The users will be creating content using the editor, and to reduce silly grammar mistakes, a chrome extension is used, [Grammarly](https://www.grammarly.com/).
But this **Grammarly extension does not work in covalent text editor**. I also followed their [steps to check if an editor is compatible or not](https://support.grammarly.com/hc/en-us/articles/115000090392-I-do-not-see-the-G-icon-on-a-certain-web-page-or-in-a-certain-text-field-but-see-it-on-other-web-pages-), and it seems this covalent editor is not compatible. 
How to resolve this issue and enable grammarly in the covalent editor?

PS: while creating this issue in github, i noticed Grammerly is working in **GitHub as its a `<text-area>`** but **Covalent editor has `<div>` tags instead of text area**. [screenshot](https://i.imgur.com/MH6YXH5.jpg)

**Comment by jeremysmartt** [comment]
Our component is just a wrapper around the simplemde library.  See this issue:
https://github.com/sparksuite/simplemde-markdown-editor/issues/586

**Comment by paulkmoore** [comment]
See Ionaru/easy-markdown-editor#133
