### ISSUE TITLE
editor very very slow

### ISSUE THREAD

**Issue by jmls** [Teradata/covalent-text-editor-nightly#7]
I am trying to implement td-text-editor in a non-material (semantic ui) project. I have just installed the td-text-editor component and imported it into my application module

As you can see, it all seems to be working

![image](https://user-images.githubusercontent.com/929523/31143627-b5e6f37c-a875-11e7-9b21-e8377a6fc9dd.png)

<td-text-editor name="description" [value]="description" [options]="{status:false, spellChecker:false, toolbar: ['bold', 'italic', 'heading', 'heading-1','heading-2','heading-3', '|', 'code','quote', '|', 'unordered-list','ordered-list','|','preview']}"></td-text-editor>'

The problem is that the editor is really slow. I mean really, really slow .. In order of >6s to add a line ..

When I check top, chrome is hitting >100% cpu while the text is rendering. As soon as the text appears, cpu drops down to 5%

Has anyone else seen this ?

Using angular 4.3.5, semantic-ui and chrome 60.0.3112.101

**Comment by jeremysmartt** [comment]
@jmls Is this still an issue?  If so can you post a stackblitz example of it?

**Comment by jmls** [comment]
seems like not in angular 6 ... there's no delay or slowness

**Comment by jeremysmartt** [comment]
ok great, so this issue can be closed out, thanks for the reply.
