### ISSUE TITLE
Use of jQuery as a language?

### ISSUE THREAD

**Issue by SGissubel** [Teradata/covalent-text-editor-nightly#9]
There are little to resources on using this particular editor. The demo on the teradata page looks beautiful... but I could not find one thing telling me how to do any of that.

**Comment by jeremysmartt** [comment]
Hello, @SGissubel Not sure exactly what you are asking for.  The Text Editor is a Markdown Editor built on top of SimpleMDE:
https://simplemde.com/

Are you actually wanting information on the Code Editor?  If so you can find the repo for it at https://github.com/Teradata/covalent-code-editor ?

**Comment by SGissubel** [comment]
Got it all figured it. The documentation was just insane to go through and figure out.  I think I nailed it though. This was three months ago... 

https://code-scissors.firebaseapp.com/
